StayMe/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('%s' % settings.URL_PREFIX, include('check_in.urls')),
    path('%s' % settings.URL_PREFIX, include('registration.urls')),
    path('%s' % settings.URL_PREFIX, include('core.urls')),
    
    path('admin/', admin.site.urls),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

check_in/urls.py
from django.urls    import path
from .views         import (IndexView, CheckInDataView, CheckInLoginView, CheckInReservationView,
                        CheckInPreAuthView, CheckInPreAuthCompleteView, CheckInFrView, CheckInCompleteView)

app_name = 'check_in'
urlpatterns = [
    path('check_in/', IndexView.as_view(), name='index'),
    path('check_in/data/', CheckInDataView.as_view(), name='data'),
    path('check_in/login/', CheckInLoginView.as_view(), name='login'),
    path('check_in/reservation/', CheckInReservationView.as_view(), name='reservation'),
    path('check_in/preauth/', CheckInPreAuthView.as_view(), name='preauth'),
    path('check_in/preauth_complete/', CheckInPreAuthCompleteView.as_view(), name='preauth_complete'),
    path('check_in/fr/', CheckInFrView.as_view(), name='fr'),
    path('check_in/complete/', CheckInCompleteView.as_view(), name='complete'),
]

core/urls.py
from django.urls    import path
from .views         import IndexView, CorePropertyView

app_name = 'core'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('property/', CorePropertyView.as_view(), name='property'),
]

check_in/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

check_in/views.py
from django.conf                import settings
from django.shortcuts           import render, redirect
from django.urls                import reverse, reverse_lazy
from django.utils.translation   import gettext, gettext_lazy as _
from django.views.generic       import *
from core                       import utils
from core.views                 import IndexView
from core.mixins                import PropertyRequiredMixin, RequestFormKwargsMixin
from .forms                     import (CheckInLoginForm, CheckInReservationForm,
                                        CheckInPreauthForm, CheckInPreauthCompleteForm, CheckInFrForm)
from .mixins                    import ParameterRequiredMixin


class IndexView(IndexView):
    pattern_name = 'check_in:login'


class CheckInDataView(RedirectView):
    pattern_name = 'check_in:login'

    def get(self, request, *args, **kwargs):
        request.session['check_in'] = {'preload': {}}
        if 'property' in request.GET: request.session['property_id'] = request.GET.get('property', None)
        if 'reservation_no' in request.GET: request.session['check_in']['preload']['reservation_no'] = request.GET.get('reservation_no', '')
        if 'check_in_date' in request.GET: request.session['check_in']['preload']['check_in_date'] = request.GET.get('check_in_date', '')
        if 'selected_reservation_no' in request.GET: request.session['check_in']['preload']['selected_reservation_no'] = request.GET.get('selected_reservation_no', '')
        return super().get(request, *args, **kwargs)


class CheckInLoginView(PropertyRequiredMixin, RequestFormKwargsMixin, FormView):
    template_name           = 'check_in/login.html'
    form_class              = CheckInLoginForm
    success_url             = reverse_lazy('check_in:reservation')
    progress_bar_module     = 'check_in'

    def dispatch(self, request, *args, **kwargs):
        if request.session.get('check_in', {}).get('preload', {}).get('auto_login', 0):
            data = {}
            data['reservation_no'] = request.session.get('check_in', {}).get('preload', {}).get('reservation_no', '')
            data['check_in_date'] = request.session.get('check_in', {}).get('preload', {}).get('check_in_date', '')
            form = self.get_form_class()
            form = form(request, data)
            if form.is_valid():
                return self.form_valid(form)
            else:
                return self.form_invalid(form)
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class CheckInReservationView(ParameterRequiredMixin, PropertyRequiredMixin, RequestFormKwargsMixin, FormView):
    template_name           = 'check_in/reservation.html'
    form_class              = CheckInReservationForm
    success_url             = reverse_lazy('check_in:preauth')
    parameter_required      = 'check_in.login'

    def dispatch(self, request, *args, **kwargs):
        data = {}
        if len(request.session.get('check_in', {}).get('login', [])) == 1:
            data['reservation_no'] = next(iter(request.session.get('check_in', {}).get('login', [])), {}).get('pmsNo', '')
        if request.session.get('check_in', {}).get('preload', {}).get('selected_reservation_no', None):
            # using `pop` to prevent issue when clicking on back button
            data['reservation_no'] = request.session.get('check_in', {}).get('preload', {}).pop('selected_reservation_no', None)
        form = self.get_form_class()
        form = form(request, data)
        if form.is_valid():
            return self.form_valid(form)
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reservations'] = []
        for reservation in self.request.session['check_in'].get('login', []):
            reservation = dict(reservation) # create new variable to prevent modification on `request.session`
            reservation['formattedArrivalDate'] = utils.format_display_date(reservation.get('arrivalDate', ''))
            reservation['formattedDepartureDate'] = utils.format_display_date(reservation.get('departureDate', ''))
            context['reservations'].append(reservation)
        return context

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        if self.request.session['check_in']['reservation'].get('status') == 'registration':
            self.success_url = reverse('registration:guest_list')
        return super().get_success_url()


class CheckInPreAuthView(ParameterRequiredMixin, PropertyRequiredMixin, RequestFormKwargsMixin, FormView):
    template_name           = 'check_in/preauth.html'
    form_class              = CheckInPreauthForm
    success_url             = reverse_lazy('check_in:preauth_complete')
    parameter_required      = 'registration.other_info'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
    

class CheckInPreAuthCompleteView(ParameterRequiredMixin, PropertyRequiredMixin, RequestFormKwargsMixin, FormView):
    template_name           = 'check_in/preauth_complete.html'
    form_class              = CheckInPreauthCompleteForm
    success_url             = reverse_lazy('check_in:fr')
    parameter_required      = 'check_in.preauth'

    def form_valid(self, form):
        form.save()
        if form.errors:
            return self.form_invalid(form)
        return super().form_valid(form)
    
    def get_success_url(self):
        if self.request.session['check_in'].get('fr'):
            self.success_url = reverse('check_in:complete')
        return super().get_success_url()


class CheckInFrView(ParameterRequiredMixin, PropertyRequiredMixin, RequestFormKwargsMixin, FormView):
    template_name           = 'check_in/fr.html'
    form_class              = CheckInFrForm
    success_url             = reverse_lazy('check_in:complete')
    parameter_required      = 'check_in.preauth'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tnc_link'] = settings.TNC_LINK
        context['privacy_link'] = settings.PRIVACY_LINK
        return context

    def form_valid(self, form):
        form.save()
        if form.errors:
            return self.form_invalid(form)
        return super().form_valid(form)


class CheckInCompleteView(TemplateView):
    template_name = 'check_in/complete.html'

check_in/templates/check_in/base.html
{% extends 'core/base.html' %}
{% load static %}

{% block page_name %}StayMe | Check In {% endblock page_name %}

{% block static_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'check_in/scss/base.scss' %}" type="text/x-scss" media="screen">
{% endblock static_css %}

{% block static_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'check_in/js/base.js' %}"></script>
{% endblock static_js %}

check_in/templates/check_in/complete.html
{% extends 'check_in/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block static_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'check_in/scss/complete.scss' %}">
{% endblock static_css %}

{% block header_left %}
    <a href="{% url 'check_in:fr' %}" class="btn btn-link"><span class="material-icons-outlined">arrow_back_ios</span></a>
    {{ block.super }}
{% endblock header_left %}

{% block content %}
    {{ block.super }}
    <div class="row page-header">
        <div class="col-12">
                Check-in Completed
        </div>
    </div>
    <div class="row page-subheader">
        <div class="col-12">
            The result below are validated from the ID and Selfie submission.
        </div>
    </div>
    <div class="row page-content">
        <div class="col-12">
            <div class="row">
                <div class="col-8">
                    ID Image:
                </div>
                <div class="col-lg-12">
                    <img width="100%" src="data:image/png;base64,{{ request.session.check_in.reservation.idImage }}"/>
                </div>
                <div class="col-8">
                    <br>
                    Selfie Image:
                </div>
                <div class="col-lg-12">
                    <img width="100%" src="data:image/png;base64,{{ request.session.check_in.reservation.fr_image }}"/>
                </div>
            </div>
            <div class="row mt-5">
                <div class="col-lg-8 mx-auto text-center {% if request.session.check_in.reservation.confidence > 80 %} text-success {% else %} text-danger {% endif %}">
                    <h5>
                        {% if request.session.check_in.reservation.confidence > 80 %}
                            Matched!
                        {% else %}
                            Face Not Matched!
                        {% endif %}
                    </h5>
                    {% if request.session.check_in.reservation.confidence > 80 %}
                    <small>Score: {{ request.session.check_in.reservation.confidence }}</small>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="row page-footer">
        <div class="col-6">
            <a href="{% url 'check_in:fr' %}" class="btn btn-outline-primary btn-side px-3">Re-submit</a>
        </div>
        <div class="col-6">
            <a href="{% url 'check_in:login' %}" class="btn btn-primary btn-side px-3">Ok</a>
        </div>
    </div>
{% endblock content %}

{% block data_js %}
    {{ block.super }}
{% endblock data_js %}

{% block static_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'check_in/js/complete.js' %}"></script>
{% endblock static_js %}

check_in/templates/check_in/fr.html
{% extends 'check_in/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block static_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'check_in/scss/fr.scss' %}" type="text/x-scss" media="screen">
{% endblock static_css %}

{% block header_left %}
    <a href="{% url 'check_in:preauth' %}" class="btn btn-link"><span class="material-icons-outlined">arrow_back_ios</span></a>
    {{ block.super }}
{% endblock header_left %}

{% block content %}
    {{ block.super }}
    <form method="post" id="form-fr" autocomplete="off">
        {% csrf_token %}
        <div class="row page-header">
            <div class="col-lg-12">
                Take a selfie
            </div>
        </div>
        <div class="row page-subheader">
            <div class="col-lg-12">
                <p class="mb-0">Please make sure:</p>
                <ol class="mb-0 pl-3">
                    <li>Environment is under optimal lighting.</li>
                    <li>Remove mask, hat, or other accessories covering your face.</li>
                    <li>Hold your phone at eye level.</li>
                </ol>
            </div>
        </div>
        <div class="row page-content">
            <div class="col-lg-12 d-flex justify-content-center">
                {% render_field form.fr_file %}
                <div class="default-container">
                    <div class="row">
                        <div class="col-lg-12">
                        </div>
                    </div>
                    <div class="row mt-5">
                        <div class="col-lg-12 text-d-neutral">
                                We are commited to protecting your privacy. By proceeding, you agree to our <a href="{{ tnc_link }}" target="_blank" class="new-window-link">Terms &amp; Conditions</a>.
                                View our Global Privacy Statement <a href="{{ privacy_link }}" target="_blank" class="new-window-link">here</a>.
                        </div>
                    </div>
                </div>
                <div class="webcam-container" style="display: none;">
                    <div class="row">
                        <div class="col-lg-12">
                            <video id="vid-webcam" autoplay width="427" height="320"/>
                        </div>
                    </div>
                    <div class="row mt-5">
                        <div class="col-lg-12 d-flex justify-content-center">
                            <button type="button" class="btn btn-primary btn-side" id="btn-capture">Capture</button>
                        </div>
                    </div>
                </div>
                <div class="preview-container" style="display: none;">
                    <img id="img-preview" width="427" height="320">
                </div>
            </div>
        </div>
        <div class="row page-footer">
            <div class="col-lg-12">
                <div class="row default-container">
                    <div class="col-lg-12 d-flex justify-content-center">
                        <button type="button" class="btn btn-primary btn-block btn-webcam">Next</button>
                    </div>
                </div>
                <div class="row preview-container" style="display: none;">
                    <div class="col-lg-6">
                        <button type="button" class="btn btn-outline-primary btn-side btn-webcam">Retake</button>
                    </div>
                    <div class="col-lg-6">
                        <button type="button" class="btn btn-primary btn-side" id="btn-next">Next</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock content %}

{% block wrapper %}
    {{ block.super }}
{% endblock wrapper %}

{% block lib_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'vendor/compressorjs/compressor.min.js' %}"></script>
{% endblock lib_js %}

{% block static_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'check_in/js/fr.js' %}"></script>
{% endblock static_js %}

check_in/templates/check_in/login.html
{% extends 'check_in/base.html' %}
{% load static %}
{% load widget_tweaks %} 

{% block lib_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'vendor/bootstrap-datepicker/bootstrap-datepicker.min.css' %}">
{% endblock lib_css %}

{% block static_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'check_in/scss/login.scss' %}" type="text/x-scss" media="screen">
{% endblock static_css %}

{% block header_left %}
    {% if not request.session.app %}
        <a href="{% url 'core:index' %}?next={{ request.path }}" class="btn btn-link">
            <span class="material-icons-outlined">home</span>
        </a>
    {% endif %}
    {{ block.super }}
{% endblock header_left %}

{% block content %}
    {{ block.super }}
    <form method="post" autocomplete="off">
        {% csrf_token %}
        <div class="row page-header">
            <div class="col-lg-12">
                Enter reservation details
            </div>
        </div>
        <div class="row page-content">
            <div class="col-lg-12">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="md-form">
                            {% if form.is_bound and form.reservation_no.errors %}
                                {% render_field form.reservation_no class="form-control is-invalid" placeholder=reservation_no_placeholder %}
                                {{ form.reservation_no.label_tag }}
                                {% for error in form.reservation_no.errors %}
                                    <div class="invalid-feedback">{{ error }}</div>
                                {% endfor %}
                            {% else %}
                                {% render_field form.reservation_no class="form-control" placeholder="e.g. 12345" %}
                                {{ form.reservation_no.label_tag }}
                                {% if form.reservation_no.help_text %}
                                    <small class="form-text text-muted">{{ form.reservation_no.help_text }}</small>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="md-form input-with-post-icon">
                            {% if form.is_bound and form.check_in_date.errors %}
                                {% render_field form.check_in_date class="form-control datepicker is-invalid" data-date-format="yyyy-mm-dd" placeholder="yyyy-mm-dd" %}
                                {{ form.check_in_date.label_tag }}
                                {% for error in form.check_in_date.errors %}
                                    <div class="invalid-feedback">{{ error }}</div>
                                {% endfor %}
                            {% else %}
                                {% render_field form.check_in_date class="form-control datepicker" data-date-format="yyyy-mm-dd" placeholder="yyyy-mm-dd" %}
                                <span class="material-icons-outlined input-prefix text-dark">date_range</span>
                                {{ form.check_in_date.label_tag }}
                                {% if form.check_in_date.help_text %}
                                    <small class="form-text text-muted">{{ form.check_in_date.help_text }}</small>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row page-footer">
            <div class="col-lg-12 d-flex justify-content-center">
                <button type="submit" class="btn btn-primary btn-block m-0" id="btn-step-next" disabled>Next</button>
            </div>
        </div>
    </form>
{% endblock content %}

{% block wrapper %}
    {{ block.super }}
    <!-- Error Modal -->
    {% for error in form.non_field_errors %}
        <div class="modal fade auto-show" id="form-error-modal-{{ forloop.counter0 }}" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header bg-primary text-white">
                        <div class="modal-title mx-auto">
                            {% if error == '2004' %}
                                Invalid Input
                            {% else %}
                                check_in_login:error_modal_title:other
                            {% endif %}
                        </div>
                    </div>
                    <div class="modal-body">
                        {% if error == '2004' %}
                            Unable to retrieve reservation information from database
                        {% else %}
                            check_in_login:error_modal_body:other
                        {% endif %}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary mx-auto" data-dismiss="modal">OK</button>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock wrapper %}

{% block lib_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'vendor/bootstrap-datepicker/bootstrap-datepicker.min.js' %}"></script>
{% endblock lib_js %}

{% block static_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'check_in/js/login.js' %}"></script>
{% endblock static_js %}

check_in/templates/check_in/preauth.html
{% extends 'check_in/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block static_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'check_in/scss/preauth.scss' %}" type="text/x-scss" media="screen">
{% endblock static_css %}

{% block header_left %}
    {% if request.session.check_in.login|length > 1 %}
        <a href="{% url 'check_in:reservation' %}" class="btn btn-link" {% if request.session.check_in.auto_login %} id="btn-skip-login" {% endif %}><span class="material-icons-outlined">arrow_back_ios</span></a>
    {% else %}
        <a href="{% url 'check_in:login' %}" class="btn btn-link" {% if request.session.check_in.auto_login %} id="btn-skip-login" {% endif %}><span class="material-icons-outlined">arrow_back_ios</span></a>
    {% endif %}
    {{ block.super }}
{% endblock header_left %}

{% block content %}
    {{ block.super }}
    <form method="post" id="form-preauth" autocomplete="off">
        {% csrf_token %}
        <div class="row page-header">
            <div class="col-12">
                Enter payment details for deposit
            </div>
        </div>
        <div class="row page-subheader">
            <div class="col-12">
                We need your credit/debit card details to charge a refundable deposit upon check-in.
            </div>
        </div>
        <div class="row page-content">
            <div class="col-12">
                <div class="row">
                    <div class="col-12">
                        <div class="border-top border-bottom py-2">
                            <div class="text-d-neutral text-center">Deposit amount (refundable)</div>
                            <div class="text-header-dark text-center">S$ 300</div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="card-wrapper"></div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="md-form">
                            {{ form.card_no.label_tag }}
                            {% if form.is_bound and form.card_no.errors %}
                                {% render_field form.card_no class="form-control is-invalid" placeholder="**** **** **** ****" %}
                                {{ form.card_no.label_tag }}
                                {% for error in form.card_no.errors %}
                                    <div class="invalid-feedback">{{ error }}</div>
                                {% endfor %}
                            {% else %}
                                {% render_field form.card_no class="form-control" placeholder="**** **** **** ****" %}
                                {{ form.card_no.label_tag }}
                                {% if form.card_no.help_text %}
                                    <small class="form-text text-muted">{{ form.card_no.help_text }}</small>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="md-form">
                            {{ form.card_username.label_tag }}
                            {% if form.is_bound and form.card_username.errors %}
                                {% render_field form.card_username class="form-control is-invalid text-transform-uppercase" placeholder="John Smith" %}
                                {{ form.card_username.label_tag }}
                                {% for error in form.card_username.errors %}
                                    <div class="invalid-feedback">{{ error }}</div>
                                {% endfor %}
                            {% else %}
                                {% render_field form.card_username class="form-control text-transform-uppercase" placeholder="John Smith" %}
                                {{ form.card_username.label_tag }}
                                {% if form.card_username.help_text %}
                                    <small class="form-text text-muted">{{ form.card_username.help_text }}</small>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <div class="md-form">
                            {{ form.card_expiry.label_tag }}
                            {% if form.is_bound and form.card_expiry.errors %}
                                {% render_field form.card_expiry class="form-control is-invalid" placeholder="MM/YYYY" %}
                                {{ form.card_expiry.label_tag }}
                                {% for error in form.card_expiry.errors %}
                                    <div class="invalid-feedback">{{ error }}</div>
                                {% endfor %}
                            {% else %}
                                {% render_field form.card_expiry class="form-control" placeholder="MM/YYYY" %}
                                {{ form.card_expiry.label_tag }}
                                {% if form.card_expiry.help_text %}
                                    <small class="form-text text-muted">{{ form.card_expiry.help_text }}</small>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="md-form">
                            {{ form.card_code.label_tag }}
                            {% if form.is_bound and form.card_code.errors %}
                                {% render_field form.card_code class="form-control is-invalid" placeholder="123" %}
                                {{ form.card_code.label_tag }}
                                {% for error in form.card_code.errors %}
                                    <div class="invalid-feedback">{{ error }}</div>
                                {% endfor %}
                            {% else %}
                                {% render_field form.card_code class="form-control" placeholder="123" %}
                                {{ form.card_code.label_tag }}
                                {% if form.card_code.help_text %}
                                    <small class="form-text text-muted">{{ form.card_code.help_text }}</small>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row page-footer">
            <div class="col-12 d-flex justify-content-center">
                <button type="submit" class="btn btn-primary btn-block m-0">Confirm</button>
            </div>
        </div>
    </form>
{% endblock content %}

{% block wrapper %}
    {{ block.super }}
    <!-- Error Modal -->
    {% for error in form.non_field_errors %}
        <div class="modal fade auto-show" id="error-modal-{{ forloop.counter0 }}" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <div class="modal-title mx-auto">Invalid Input</div>
                    </div>
                    <div class="modal-body">
                        {{ error|linebreaks }}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary mx-auto" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock wrapper %}

{% block lib_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'vendor/card/jquery.card.js' %}"></script>
{% endblock lib_js %}

{% block static_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'check_in/js/preauth.js' %}"></script>
{% endblock static_js %}